### ISSUE TITLE
audio_hw.c with audio_policy.c 

### ISSUE THREAD

**Issue by PatilSiddhesh** [7420dev/android_device_samsung_zerofltexx#4]
stock files from aosp should work 
[audio.zip](https://github.com/7420dev/android_device_samsung_zerofltexx/files/61506/audio.zip)

**Comment by eleboucher** [comment]
Things you can try is to flash cm and replace with that if it's working then you're right

**Comment by arter97** [comment]
lol no it won't work.

**Comment by PatilSiddhesh** [comment]
oh. my bad, you are using a custom audio hal.
